config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "exchange_rates#index"
  resources :exchange_rates
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exchange_rate.rb
# frozen_string_literal: true

class ExchangeRate < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/exchange_rates_controller.rb
# frozen_string_literal: true

class ExchangeRatesController < ApplicationController
  before_action :set_exchange_rate, only: %i[show edit update destroy]

  # GET /exchange_rates
  def index
    @exchange_rates = ExchangeRate.all
  end

  # GET /exchange_rates/1
  def show; end

  # GET /exchange_rates/new
  def new
    @exchange_rate = ExchangeRate.new
  end

  # GET /exchange_rates/1/edit
  def edit; end

  # POST /exchange_rates
  def create
    @exchange_rate = ExchangeRate.new(exchange_rate_params)

    if @exchange_rate.save
      redirect_to @exchange_rate,
                  notice: _("Exchange rate was successfully created.")
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /exchange_rates/1
  def update
    if @exchange_rate.update(exchange_rate_params)
      redirect_to @exchange_rate,
                  notice: _("Exchange rate was successfully updated.")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /exchange_rates/1
  def destroy
    @exchange_rate.destroy
    redirect_to exchange_rates_url,
                notice: _("Exchange rate was successfully destroyed.")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exchange_rate
    @exchange_rate = ExchangeRate.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def exchange_rate_params
    params.require(:exchange_rate).permit(:from_currency, :to_currency, :amount)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/exchange_rates_helper.rb
# frozen_string_literal: true

module ExchangeRatesHelper
end

app/views/exchange_rates/_exchange_rate.html.erb
<div id="<%= dom_id exchange_rate %>">
  <p>
    <strong>From currency:</strong> <%= exchange_rate.from_currency %>
  </p>

  <p>
    <strong>To currency:</strong> <%= exchange_rate.to_currency %>
  </p>

  <p>
    <strong>Amount:</strong> <%= exchange_rate.amount %>
  </p>
</div>

app/views/exchange_rates/_form.html.erb
<%= form_with(model: exchange_rate) do |form| %>
  <% if exchange_rate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exchange_rate.errors.count, "error") %> prohibited this exchange_rate from being saved:</h2>

      <ul>
        <% exchange_rate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :from_currency, style: "display: block" %>
    <%= form.text_field :from_currency %>
  </div>

  <div>
    <%= form.label :to_currency, style: "display: block" %>
    <%= form.text_field :to_currency %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exchange_rates/edit.html.erb
<h1>Editing exchange rate</h1>

<%= render "form", exchange_rate: @exchange_rate %>

<br>

<div>
  <%= link_to "Show this exchange rate", @exchange_rate %> |
  <%= link_to "Back to exchange rates", exchange_rates_path %>
</div>

app/views/exchange_rates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Exchange rates</h1>

<div id="exchange_rates">
  <% @exchange_rates.each do |exchange_rate| %>
    <%= render exchange_rate %>
    <p>
      <%= link_to "Show this exchange rate", exchange_rate %>
    </p>
  <% end %>
</div>

<%= link_to "New exchange rate", new_exchange_rate_path %>

app/views/exchange_rates/new.html.erb
<h1>New exchange rate</h1>

<%= render "form", exchange_rate: @exchange_rate %>

<br>

<div>
  <%= link_to "Back to exchange rates", exchange_rates_path %>
</div>

app/views/exchange_rates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exchange_rate %>

<div>
  <%= link_to "Edit this exchange rate", edit_exchange_rate_path(@exchange_rate) %> |
  <%= link_to "Back to exchange rates", exchange_rates_path %>

  <%= button_to "Destroy this exchange rate", @exchange_rate, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>